apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-video-svc
  template:
    metadata:
      labels:
        app: stream-video-svc
    spec:
      containers:
      - name: stream-video-svc
        image: dreadflixbackend.azurecr.io/samples/stream:latest
        ports:
        - containerPort: 3007
---
apiVersion: v1
kind: Service
metadata:
  name: stream-video-svc
  namespace: default
  labels:
    app: stream-video-svc
spec:
  selector:
    app: stream-video-svc
  ports:
    - protocol: TCP
      port: 3007
      targetPort: 3007
  type: LoadBalancer