apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-service
  template:
    metadata:
      labels:
        app: stream-service
    spec:
      containers:
      - name: stream-service
        image: 961341555113.dkr.ecr.us-east-1.amazonaws.com/stream-service:latest
        ports:
        - containerPort: 3007
---
apiVersion: v1
kind: Service
metadata:
  name: stream-video-service
  namespace: default
  labels:
    app: stream-video-service
spec:
  selector:
    app: stream-service
  ports:
    - protocol: TCP
      port: 3007
      targetPort: 3007
  type: NodePort