name: Build and Deploy to AKS

on:
  push:
    branches:
      - main  # Run when changes are pushed to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to ACR
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login dreadflixbackend.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t dreadflixbackend.azurecr.io/samples/stream:${{ github.sha }} .
          docker tag dreadflixbackend.azurecr.io/samples/stream:${{ github.sha }} dreadflixbackend.azurecr.io/samples/stream:latest
          docker push dreadflixbackend.azurecr.io/samples/stream:${{ github.sha }}
          docker push dreadflixbackend.azurecr.io/samples/stream:latest


  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure using Service Principal
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Set Azure subscription
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group DefaultResourceGroup-EUS --name dreadflix
          
      - name: Deploy to AKS
        run: |
          kubectl rollout restart deployment/stream-deployment
